
[sensing]
    dockerfile = "Dockerfile"
    compose_partial = "snippet.yml"
    volume.data.path = "/app/data"
    volume.user_config.path = "/app/user_config"
    volume.udev.path = "/run/udev"
    volume.udev.mode = "ro"